name: GitHub Actions Demo
on: workflow_dispatch
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python job.py
      - run: echo "Ceci est un fichier généré par la pipeline!" > output.txt
      - run: cat output.txt
      - uses: actions/upload-artifact@v4
        with:
          name: output-artifact
          path: output.txt